-- ============================================================
-- SNEAKER AIR — Migration for an EXISTING "Dress Code" database
-- Run this in the Supabase SQL Editor on a DB that already has the
-- old products/orders tables. It is non-destructive: it adds the
-- missing column + tables and locks down RLS. It does NOT delete or
-- overwrite existing product/order rows.
--
-- To also REPLACE the old clothing catalog with the sneaker catalog,
-- run lib/supabase-schema.sql section 8 after truncating products, OR
-- manage products from the admin panel. (Left manual on purpose so we
-- never clobber live inventory.)
-- ============================================================

-- 1. Orders: add the missing fulfillment `status` column (root cause of
--    failing checkout inserts, failed webhook order creation, and the
--    admin "change status" error).
ALTER TABLE orders ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'pending';
CREATE INDEX IF NOT EXISTS idx_orders_status ON orders(status);

-- 2. Create the three tables the code writes to but that never existed.
CREATE TABLE IF NOT EXISTS sales_collections (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL DEFAULT 'Unnamed Collection',
  description TEXT NOT NULL DEFAULT '',
  discount_percentage DECIMAL(5, 2) NOT NULL DEFAULT 0,
  image_url TEXT NOT NULL DEFAULT '',
  product_ids JSONB NOT NULL DEFAULT '[]',
  is_active BOOLEAN NOT NULL DEFAULT true,
  start_date TIMESTAMPTZ,
  end_date TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_sales_collections_is_active ON sales_collections(is_active);

CREATE TABLE IF NOT EXISTS newsletter_subscribers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  subscribed_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS contact_submissions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT NOT NULL,
  name TEXT NOT NULL DEFAULT '',
  message TEXT NOT NULL DEFAULT '',
  date TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 3. Lock down RLS. Remove the old wide-open "allow everything to anon"
--    policies and replace with: public read-only catalog, deny-all else.
ALTER TABLE products               ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders                 ENABLE ROW LEVEL SECURITY;
ALTER TABLE sales_collections      ENABLE ROW LEVEL SECURITY;
ALTER TABLE newsletter_subscribers ENABLE ROW LEVEL SECURITY;
ALTER TABLE contact_submissions    ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Products are publicly readable"        ON products;
DROP POLICY IF EXISTS "Allow all product operations for now"  ON products;
DROP POLICY IF EXISTS "Anyone can create orders (checkout)"   ON orders;
DROP POLICY IF EXISTS "Allow all order operations for now"    ON orders;

DROP POLICY IF EXISTS "products_public_read" ON products;
CREATE POLICY "products_public_read"
  ON products FOR SELECT
  TO anon, authenticated
  USING (true);

-- orders / sales_collections / newsletter_subscribers / contact_submissions:
-- RLS enabled with NO anon policy => anon denied. All app access is via the
-- service-role key (supabaseAdmin), which bypasses RLS.

-- 4. Optional: default new products to a sneaker category instead of 'dresses'.
ALTER TABLE products ALTER COLUMN category SET DEFAULT 'lifestyle';
