-- ============================================================
-- SNEAKER AIR — E-Commerce Supabase Schema (full setup)
-- Run this in your Supabase SQL Editor: https://app.supabase.com/project/_/sql
-- Idempotent: safe to run on a fresh project. For an EXISTING DB that
-- already had the old "Dress Code" schema, run lib/supabase-migration.sql instead.
-- ============================================================

-- ==========================================
-- 1. PRODUCTS
-- ==========================================
CREATE TABLE IF NOT EXISTS products (
  id BIGINT PRIMARY KEY,
  name TEXT NOT NULL DEFAULT 'Unnamed Sneaker',
  price DECIMAL(10, 2) NOT NULL DEFAULT 0,
  category TEXT NOT NULL DEFAULT 'lifestyle',
  description TEXT NOT NULL DEFAULT '',
  images TEXT[] NOT NULL DEFAULT '{}',
  sizes JSONB NOT NULL DEFAULT '[]',
  colors JSONB NOT NULL DEFAULT '[]',
  is_new BOOLEAN NOT NULL DEFAULT false,
  is_featured BOOLEAN NOT NULL DEFAULT false,
  stock INTEGER NOT NULL DEFAULT 100,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_products_category ON products(category);
CREATE INDEX IF NOT EXISTS idx_products_is_new ON products(is_new);
CREATE INDEX IF NOT EXISTS idx_products_is_featured ON products(is_featured);

-- ==========================================
-- 2. ORDERS  (note: BOTH payment_status AND status columns)
-- ==========================================
CREATE TABLE IF NOT EXISTS orders (
  id TEXT PRIMARY KEY,
  items JSONB NOT NULL DEFAULT '[]',
  customer JSONB NOT NULL DEFAULT '{}',
  total DECIMAL(10, 2) NOT NULL DEFAULT 0,
  subtotal DECIMAL(10, 2) NOT NULL DEFAULT 0,
  shipping DECIMAL(10, 2) NOT NULL DEFAULT 0,
  payment_fee DECIMAL(10, 2) NOT NULL DEFAULT 0,
  payment_method TEXT NOT NULL DEFAULT 'cash_on_delivery',
  payment_status TEXT NOT NULL DEFAULT 'pending',
  status TEXT NOT NULL DEFAULT 'pending',            -- fulfillment status (pending/processing/shipped/delivered/cancelled)
  date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_orders_date ON orders(date DESC);
CREATE INDEX IF NOT EXISTS idx_orders_payment_status ON orders(payment_status);
CREATE INDEX IF NOT EXISTS idx_orders_status ON orders(status);
CREATE INDEX IF NOT EXISTS idx_orders_customer_email ON orders USING btree ((customer->>'email'));

-- ==========================================
-- 3. SALES COLLECTIONS  (promotional bundles / campaigns)
-- ==========================================
CREATE TABLE IF NOT EXISTS sales_collections (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL DEFAULT 'Unnamed Collection',
  description TEXT NOT NULL DEFAULT '',
  discount_percentage DECIMAL(5, 2) NOT NULL DEFAULT 0,
  image_url TEXT NOT NULL DEFAULT '',
  product_ids JSONB NOT NULL DEFAULT '[]',
  is_active BOOLEAN NOT NULL DEFAULT true,
  start_date TIMESTAMPTZ,
  end_date TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_sales_collections_is_active ON sales_collections(is_active);

-- ==========================================
-- 4. NEWSLETTER SUBSCRIBERS
-- ==========================================
CREATE TABLE IF NOT EXISTS newsletter_subscribers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  subscribed_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ==========================================
-- 5. CONTACT SUBMISSIONS
-- ==========================================
CREATE TABLE IF NOT EXISTS contact_submissions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT NOT NULL,
  name TEXT NOT NULL DEFAULT '',
  message TEXT NOT NULL DEFAULT '',
  date TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ==========================================
-- 6. ROW LEVEL SECURITY
-- ------------------------------------------
-- The app performs ALL reads/writes server-side via the SERVICE ROLE key
-- (lib/supabase.ts -> supabaseAdmin), which BYPASSES RLS. So the policies
-- below intentionally grant the public/anon role ONLY what a browser could
-- ever legitimately need: read-only product catalog. Everything else
-- (orders/PII, collections management, newsletter, contact) has RLS enabled
-- with NO anon policy => anon is denied. This closes the previous hole where
-- "FOR ALL USING(true)" let anyone with the public anon key read all orders
-- and mutate the catalog directly through the Supabase REST endpoint.
-- ==========================================
ALTER TABLE products               ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders                 ENABLE ROW LEVEL SECURITY;
ALTER TABLE sales_collections      ENABLE ROW LEVEL SECURITY;
ALTER TABLE newsletter_subscribers ENABLE ROW LEVEL SECURITY;
ALTER TABLE contact_submissions    ENABLE ROW LEVEL SECURITY;

-- Drop any legacy wide-open policies if present (from the old schema)
DROP POLICY IF EXISTS "Products are publicly readable"        ON products;
DROP POLICY IF EXISTS "Allow all product operations for now"  ON products;
DROP POLICY IF EXISTS "Anyone can create orders (checkout)"   ON orders;
DROP POLICY IF EXISTS "Allow all order operations for now"    ON orders;

-- Products: anon may READ only. No anon insert/update/delete (service role handles writes).
DROP POLICY IF EXISTS "products_public_read" ON products;
CREATE POLICY "products_public_read"
  ON products FOR SELECT
  TO anon, authenticated
  USING (true);

-- Orders / sales_collections / newsletter / contact:
-- RLS enabled + no anon policy => anon fully denied. Service role bypasses RLS.
-- (No policies created on purpose.)

-- ==========================================
-- 7. AUTO updated_at TRIGGER (products)
-- ==========================================
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS update_products_updated_at ON products;
CREATE TRIGGER update_products_updated_at
  BEFORE UPDATE ON products
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- ==========================================
-- 8. SEED SNEAKER CATALOG (must mirror data/products.ts)
--    Sizes are EU (38–46) with per-size stock. Currency: EUR.
-- ==========================================
INSERT INTO products (id, name, price, category, description, images, sizes, colors, is_new, is_featured, stock)
VALUES
  (1, 'Air Apex Runner', 149.99, 'running',
   'The flagship Sneaker Air daily trainer. A responsive nitrogen-infused foam midsole and engineered mesh upper deliver plush cushioning with a locked-in, breathable fit for every mile.',
   ARRAY['https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80','https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?w=800&q=80'],
   '[{"name":"38","available":true,"stock":8},{"name":"39","available":true,"stock":12},{"name":"40","available":true,"stock":15},{"name":"41","available":true,"stock":14},{"name":"42","available":true,"stock":10},{"name":"43","available":true,"stock":9},{"name":"44","available":false,"stock":0},{"name":"45","available":true,"stock":6},{"name":"46","available":true,"stock":4}]'::jsonb,
   '[{"name":"Crimson Pulse","hex":"#e11d48","available":true},{"name":"Core Black","hex":"#111111","available":true},{"name":"Cloud White","hex":"#f5f5f5","available":true}]'::jsonb,
   true, true, 78),

  (2, 'Velocity Boost Pro', 169.99, 'running',
   'A race-day speed shoe with a carbon-infused propulsion plate and a feather-light knit upper. Built for tempo runs and personal bests.',
   ARRAY['https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=800&q=80','https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=800&q=80'],
   '[{"name":"38","available":true,"stock":5},{"name":"39","available":true,"stock":7},{"name":"40","available":true,"stock":11},{"name":"41","available":true,"stock":13},{"name":"42","available":true,"stock":12},{"name":"43","available":false,"stock":0},{"name":"44","available":true,"stock":8},{"name":"45","available":true,"stock":5},{"name":"46","available":true,"stock":3}]'::jsonb,
   '[{"name":"Volt Green","hex":"#84cc16","available":true},{"name":"Ice Blue","hex":"#38bdf8","available":true}]'::jsonb,
   false, true, 64),

  (3, 'Skyline Dunk High', 189.99, 'basketball',
   'A high-top hardwood icon reborn. Full-grain leather panels, a padded collar and a herringbone-traction outsole for lockdown and ankle support on court.',
   ARRAY['https://images.unsplash.com/photo-1584735175315-9d5df23860e6?w=800&q=80','https://images.unsplash.com/photo-1552346154-21d32810aba3?w=800&q=80'],
   '[{"name":"38","available":true,"stock":6},{"name":"39","available":true,"stock":9},{"name":"40","available":true,"stock":12},{"name":"41","available":true,"stock":10},{"name":"42","available":true,"stock":11},{"name":"43","available":true,"stock":7},{"name":"44","available":true,"stock":5},{"name":"45","available":false,"stock":0},{"name":"46","available":true,"stock":2}]'::jsonb,
   '[{"name":"Court Purple","hex":"#7c3aed","available":true},{"name":"Black/White","hex":"#1f2937","available":true},{"name":"University Red","hex":"#dc2626","available":true}]'::jsonb,
   true, true, 62),

  (4, 'Court Legend ''85', 159.99, 'basketball',
   'A heritage low-top inspired by the golden era of the game. Clean leather lines, a vintage gum sole and timeless colour-blocking.',
   ARRAY['https://images.unsplash.com/photo-1600269452121-4f2416e55c28?w=800&q=80','https://images.unsplash.com/photo-1549298916-b41d501d3772?w=800&q=80'],
   '[{"name":"38","available":true,"stock":7},{"name":"39","available":true,"stock":8},{"name":"40","available":true,"stock":10},{"name":"41","available":true,"stock":9},{"name":"42","available":false,"stock":0},{"name":"43","available":true,"stock":6},{"name":"44","available":true,"stock":5},{"name":"45","available":true,"stock":4},{"name":"46","available":true,"stock":3}]'::jsonb,
   '[{"name":"Sail/Gum","hex":"#e7e0cf","available":true},{"name":"Varsity Blue","hex":"#2563eb","available":true}]'::jsonb,
   false, false, 52),

  (5, 'Metro Lifestyle Low', 119.99, 'lifestyle',
   'The everyday off-court staple. Soft suede overlays, a cushioned sockliner and a low profile that pairs with anything in your rotation.',
   ARRAY['https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=800&q=80','https://images.unsplash.com/photo-1595341888016-a392ef81b7de?w=800&q=80'],
   '[{"name":"38","available":true,"stock":14},{"name":"39","available":true,"stock":16},{"name":"40","available":true,"stock":18},{"name":"41","available":true,"stock":15},{"name":"42","available":true,"stock":13},{"name":"43","available":true,"stock":11},{"name":"44","available":true,"stock":9},{"name":"45","available":true,"stock":6},{"name":"46","available":false,"stock":0}]'::jsonb,
   '[{"name":"Stone Grey","hex":"#9ca3af","available":true},{"name":"Off White","hex":"#faf9f6","available":true},{"name":"Olive","hex":"#4d7c0f","available":true}]'::jsonb,
   false, true, 102),

  (6, 'Cloud Drift Knit', 139.99, 'lifestyle',
   'A slip-on cloud for the city. A one-piece stretch-knit upper hugs the foot while a super-critical foam sole floats every step.',
   ARRAY['https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?w=800&q=80','https://images.unsplash.com/photo-1512374382149-233c42b6a83b?w=800&q=80'],
   '[{"name":"38","available":true,"stock":10},{"name":"39","available":true,"stock":12},{"name":"40","available":true,"stock":13},{"name":"41","available":true,"stock":11},{"name":"42","available":true,"stock":10},{"name":"43","available":false,"stock":0},{"name":"44","available":true,"stock":7},{"name":"45","available":true,"stock":5},{"name":"46","available":true,"stock":3}]'::jsonb,
   '[{"name":"Misty Rose","hex":"#fecdd3","available":true},{"name":"Slate","hex":"#475569","available":true}]'::jsonb,
   true, false, 71),

  (7, 'Grind Skate Classic', 99.99, 'skate',
   'A vulcanised skate workhorse. A grippy waffle outsole, reinforced ollie zones and a padded tongue built to take a beating at the park.',
   ARRAY['https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=800&q=80','https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?w=800&q=80'],
   '[{"name":"38","available":true,"stock":9},{"name":"39","available":true,"stock":11},{"name":"40","available":true,"stock":13},{"name":"41","available":true,"stock":12},{"name":"42","available":true,"stock":10},{"name":"43","available":true,"stock":8},{"name":"44","available":false,"stock":0},{"name":"45","available":true,"stock":4},{"name":"46","available":true,"stock":2}]'::jsonb,
   '[{"name":"Black/Gum","hex":"#1c1917","available":true},{"name":"Navy","hex":"#1e3a8a","available":true}]'::jsonb,
   false, false, 69),

  (8, 'Halfpipe Suede', 109.99, 'skate',
   'Retro skate style meets modern impact protection. Plush suede, a herringbone grip and a hidden foam heel insert for landing bigger drops.',
   ARRAY['https://images.unsplash.com/photo-1465453869711-7e174808ace9?w=800&q=80','https://images.unsplash.com/photo-1552346154-21d32810aba3?w=800&q=80'],
   '[{"name":"38","available":true,"stock":6},{"name":"39","available":true,"stock":8},{"name":"40","available":true,"stock":10},{"name":"41","available":true,"stock":9},{"name":"42","available":true,"stock":7},{"name":"43","available":true,"stock":6},{"name":"44","available":true,"stock":4},{"name":"45","available":false,"stock":0},{"name":"46","available":true,"stock":2}]'::jsonb,
   '[{"name":"Rust","hex":"#b45309","available":true},{"name":"Forest","hex":"#166534","available":true}]'::jsonb,
   true, false, 52),

  (9, 'Forge Trainer X', 129.99, 'training',
   'A stable, flat-platform trainer for the gym floor. A wide base for lifts, a rope-guard midfoot wrap and breathable mesh for high-output sessions.',
   ARRAY['https://images.unsplash.com/photo-1518002171953-a080ee817e1f?w=800&q=80','https://images.unsplash.com/photo-1539185441755-769473a23570?w=800&q=80'],
   '[{"name":"38","available":true,"stock":8},{"name":"39","available":true,"stock":10},{"name":"40","available":true,"stock":12},{"name":"41","available":true,"stock":11},{"name":"42","available":true,"stock":9},{"name":"43","available":true,"stock":7},{"name":"44","available":true,"stock":5},{"name":"45","available":true,"stock":4},{"name":"46","available":false,"stock":0}]'::jsonb,
   '[{"name":"Graphite","hex":"#374151","available":true},{"name":"Signal Orange","hex":"#f97316","available":true}]'::jsonb,
   false, true, 66),

  (10, 'Circuit Cross', 124.99, 'training',
   'A versatile cross-trainer for HIIT and the track. Multi-surface traction, a locked-down midfoot cage and responsive cushioning for jumps and sprints.',
   ARRAY['https://images.unsplash.com/photo-1539185441755-769473a23570?w=800&q=80','https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=800&q=80'],
   '[{"name":"38","available":true,"stock":7},{"name":"39","available":true,"stock":9},{"name":"40","available":true,"stock":11},{"name":"41","available":true,"stock":10},{"name":"42","available":false,"stock":0},{"name":"43","available":true,"stock":6},{"name":"44","available":true,"stock":5},{"name":"45","available":true,"stock":3},{"name":"46","available":true,"stock":2}]'::jsonb,
   '[{"name":"Teal","hex":"#0d9488","available":true},{"name":"Black","hex":"#0a0a0a","available":true}]'::jsonb,
   false, false, 53),

  (11, 'Phantom Limited "Eclipse"', 249.99, 'limited',
   'A numbered Sneaker Air drop. Blacked-out premium leather, a translucent smoke outsole and reflective 3M detailing that ignites under light.',
   ARRAY['https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=800&q=80','https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?w=800&q=80'],
   '[{"name":"38","available":false,"stock":0},{"name":"39","available":true,"stock":3},{"name":"40","available":true,"stock":4},{"name":"41","available":true,"stock":5},{"name":"42","available":true,"stock":4},{"name":"43","available":true,"stock":3},{"name":"44","available":true,"stock":2},{"name":"45","available":false,"stock":0},{"name":"46","available":true,"stock":1}]'::jsonb,
   '[{"name":"Eclipse Black","hex":"#0b0b0f","available":true}]'::jsonb,
   true, true, 22),

  (12, 'Aurora Limited "Prism"', 269.99, 'limited',
   'A collector''s grail with an iridescent shifting upper, gradient tooling and premium co-ordinated lace sets. Extremely limited quantities.',
   ARRAY['https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=800&q=80','https://images.unsplash.com/photo-1552346154-21d32810aba3?w=800&q=80'],
   '[{"name":"38","available":true,"stock":2},{"name":"39","available":true,"stock":3},{"name":"40","available":true,"stock":4},{"name":"41","available":true,"stock":3},{"name":"42","available":true,"stock":2},{"name":"43","available":false,"stock":0},{"name":"44","available":true,"stock":2},{"name":"45","available":true,"stock":1},{"name":"46","available":false,"stock":0}]'::jsonb,
   '[{"name":"Prism Iridescent","hex":"#a78bfa","available":true}]'::jsonb,
   true, false, 19)

ON CONFLICT (id) DO NOTHING;
